WITH PNUMBER AS (
    SELECT P.PRODUCT_ID, PRODUCT_NAME, PRICE, SUM(AMOUNT) AS NUM
    FROM FOOD_PRODUCT AS P INNER JOIN FOOD_ORDER AS O
        ON P.PRODUCT_ID = O.PRODUCT_ID
    WHERE PRODUCE_DATE LIKE '2022-05%'
    GROUP BY 1
)

SELECT PRODUCT_ID, PRODUCT_NAME,
    (PRICE * NUM) AS TOTAL_SALES
FROM PNUMBER
ORDER BY 3 DESC, 1