WITH CALCULATE AS (
    SELECT U.USER_ID, YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER
    FROM USER_INFO AS U INNER JOIN ONLINE_SALE AS O
        ON U.USER_ID = O.USER_ID
    WHERE GENDER IS NOT NULL
)

SELECT YEAR, MONTH, GENDER, COUNT(DISTINCT USER_ID) AS USERS
FROM CALCULATE
GROUP BY 1, 2, 3
ORDER BY 1, 2, 3