WITH CHARGE AS (
    SELECT CAR_ID, C.CAR_TYPE,
        (DAILY_FEE * 30 * (1 - DISCOUNT_RATE / 100)) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR AS C INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D
        ON C.CAR_TYPE = D.CAR_TYPE
    WHERE (C.CAR_TYPE = 'SUV' OR C.CAR_TYPE = '세단')
        AND DURATION_TYPE = '30일 이상'
),

USE_DATE AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY 1
    HAVING MAX(END_DATE) < '2022-11-01'
)

SELECT DISTINCT C.CAR_ID, CAR_TYPE, ROUND(FEE)
FROM CHARGE AS C INNER JOIN USE_DATE AS U
    ON C.CAR_ID = U.CAR_ID
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY 3 DESC, 2, 1 DESC