WITH JAN AS (
    SELECT BOOK_ID, SUM(SALES) AS CNT
    FROM BOOK_SALES
    WHERE SALES_DATE LIKE '2022-01%'
    GROUP BY 1
),

BOOK_INFO AS (
    SELECT BOOK_ID, B.AUTHOR_ID, AUTHOR_NAME, CATEGORY, PRICE
    FROM BOOK AS B INNER JOIN AUTHOR AS A
        ON B.AUTHOR_ID = A.AUTHOR_ID
)

SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY,
    SUM(CNT * PRICE) AS TOTAL_SALES
FROM JAN AS J INNER JOIN BOOK_INFO AS BI
    ON J.BOOK_ID = BI.BOOK_ID
GROUP BY 1, 3
ORDER BY 1, 3 DESC