WITH RENTAL AS (
    SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE, H.HISTORY_ID, D.DURATION_TYPE, 
        COALESCE(D.DISCOUNT_RATE, 0) AS DISCOUNT_RATE,
        DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS RENTAL_DATE
    FROM CAR_RENTAL_COMPANY_CAR AS C
    INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
        ON C.CAR_ID = H.CAR_ID
    LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D
        ON C.CAR_TYPE = D.CAR_TYPE
        AND (
            D.DURATION_TYPE = CASE 
                                 WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
                                 WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
                                 WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN '7일 이상'
                               END
        )
    WHERE C.CAR_TYPE = '트럭'
)

SELECT HISTORY_ID,
    ROUND(DAILY_FEE * RENTAL_DATE * (1 - DISCOUNT_RATE / 100)) AS FEE
FROM RENTAL
ORDER BY 2 DESC, 1 DESC