WITH 1ST AS (
    SELECT ID FROM ECOLI_DATA WHERE PARENT_ID IS NULL
),

PANDK AS (
    SELECT E1.PARENT_ID AS G_ID, E1.ID AS P_ID, E2.ID AS K_ID
    FROM ECOLI_DATA AS E1 INNER JOIN ECOLI_DATA AS E2
        ON E1.ID = E2.PARENT_ID
)

SELECT K_ID AS ID
FROM PANDK AS P INNER JOIN 1ST AS F
    ON P.G_ID = F.ID
ORDER BY 1