SELECT F.FLAVOR
FROM FIRST_HALF AS F INNER JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS SUM_ORDER
    FROM JULY
    GROUP BY FLAVOR) AS J
        ON F.FLAVOR = J.FLAVOR
ORDER BY (F.TOTAL_ORDER + J.SUM_ORDER) DESC
LIMIT 3